"""empty message

Revision ID: 573cdbcbb1e7
Revises: 3b0da06c44ab
Create Date: 2019-03-12 20:12:40.865150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573cdbcbb1e7'
down_revision = '3b0da06c44ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('posts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    # ### end Alembic commands ###
